site_name: d6dice
site_author: Chuck Mo
copyright: GPLv3
repo_url: https://gitlab.com/thechuckmo/d6dice
google_analytics: [UA-138667896-1, d6engine.org]

theme: 
   name: cluster

extra:
    fa_logo: 'fa-dice-one'
    #    prev_next_enabled: True
    #    nav_right: ['Install', 'DevSetup', 'Examples']
    #    hidden: ['Home']

